name: chromix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^10.1.2
  auto_route_generator: ^10.2.4
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  get_it: ^8.0.3
  get_storage: ^2.1.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  provider: ^6.0.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  solid_lints: ^0.3.1

dependency_overrides:
  intl:

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: ""
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: lstBold
      fonts:
        - asset: fonts/LibreCaslonText-Bold.ttf

flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
